name: Makefile CI

on:
  push:
    branches: [ "main", "novalidation-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: arch -x86_64 make
    
    - name: generate token
      run: arch -x86_64 ./token-generator
