name: Makefile CI

on:
  push:
    branches: [ "main", "novalidation-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: install rosetta
      run: "/usr/sbin/softwareupdate -install-rosetta -agree-to-license"

    - name: Install dependencies
      run: arch -arm64 make
    
    - name: generate token
      run: arch -arm64 ./token-generator
